# action.yml
name: 'Run Lighthouse CI on Shopify theme'
branding:
  icon: shopping-bag
  colour: green
description: 'Run Lighthouse CI on Shopify themes directly from GitHub'
inputs:
  access_token:
    description: 'Custom app access token'
    # required: false because you can still authenticate with private
    # app credentials
    required: false
  store:
    description: '<domain>.myshopify.com URL'
    required: true
  password:
    description: 'Password-protected shop password'
    required: false
  product_handle:
    description: 'Product handle for product page test (default: first product).'
    required: false
  collection_handle:
    description: 'Collection handle for collection page test (default: first collection).'
    required: false
  theme_root:
    description: 'The root folder for the theme files that will be uploaded (default: ".")'
    required: false
    default: '.'
  pull_theme:
    description: 'The ID or name of a theme from which the settings and JSON templates should be pulled. If provided, those settings will be pulled into the development theme.'
    required: false
  lhci_server_url:
    description: "Changes upload target to lhci"
    required: false
  lhci_build_token:
    description: "Required when using lhci_server_url"
    required: false
  lhci_github_app_token:
    description: 'Lighthouse CI GitHub app token'
    required: false
  lhci_github_token:
    description: 'GitHub personal access token'
    required: false
  lhci_min_score_performance:
    description: 'Minimum performance score'
    required: false
    default: 0.6
  lhci_min_score_accessibility:
    description: 'Minimum accessibility score'
    required: false
    default: 0.9
  github_actor:
    description: 'GitHub actor'
    required: false
  github_token:
    description: 'GitHub personal access token'
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}
    - name: docker
      uses: docker://ghcr.io/wosg-usa/lighthouse-ci-action:latest
      with:
        entrypoint: /entrypoint.sh
