FROM node:20-bookworm

ENV PATH="/root/.rbenv/shims:${PATH}"

# Shopify CLI does not require Ruby

# Puppeteer includes Chrome

# install puppeteer and stuff
ENV npm_config_prefix="$GITHUB_WORKSPACE/.node"
ENV PATH="$npm_config_prefix:${PATH}"
RUN mkdir -p "$npm_config_prefix" \
  && chmod -R 777 "$npm_config_prefix" \
  && umask 000 \
  && npm install -g @lhci/cli@0.14.x lighthouse puppeteer
